### ISSUE TITLE
Aura not responding to changes in Synapse

### ISSUE THREAD

**Issue by bartekpasiecznik** [AndrewBabbitt97/AuraConnect#5] opened 2019-10-11 08:48 UTC
I have the newest versions of Synapse and Aura. Aura device shows in Synapse but when I change the colours, it doesn't change it on my computer. When I look in Aura sync, it shows "select effect"
I have 2 tridentz rgb, rtx 2080 strix and Asus prime a z370

**Comment by Ellargo333** [comment] 2019-10-12 17:19
Hi!.. I have the same problem!
Tridentz RGB, ASUS GTX 1070... ASUS Prime X470 Pro.

**Comment by AndrewBabbitt97** [comment] 2019-10-13 01:45
Looks like maybe a dupe of #4.

I'm thinking I might do a diagnostic utility soon to collect system info on hardware. This could be useful for seeing what's going on.

When this is added I'd like both of you to run this if possible.

**Comment by heavyoak** [comment] 2019-10-25 20:19
same issue.

**Comment by PeakDreamz** [comment] 2019-12-18 05:55
I had the same issue however I got it to work. Not sure this did anything but I disabled other devices in aura sync, deleted lighting effects previously in razer and then restarted. I think the restart was the biggest help. Now my Hero VIII, Gkill, and Castle 360 rad play  wonderfully together! THank you Andrew. Will look for a BTC address to send a tip.

**Comment by AndrewBabbitt97** [comment] 2020-01-10 04:53
New release is out, please test this new release and let me know how things are in it:

https://github.com/AndrewBabbitt97/AuraConnect/releases/tag/1.0.1

**Closed** 2020-02-19 01:39 UTC
