### ISSUE TITLE
Aura Connect Service breaking sleep

### ISSUE THREAD

**Issue by Funkybrunk** [AndrewBabbitt97/AuraConnect#90] opened 2020-10-24 17:19 UTC
Hello!

I first wanted to say, beautiful work, this is working perfect on my new Asus mobo and Razer peripherals. I am running into an issue though, when I stop the aura connect service, the computer will go to sleep properly. With the service enabled, the machine will not sleep automatically. I can still make the machine sleep manually. Please let me know if there are any logs/specs I can provide to assist in diagnosing the cause.

Thanks!
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5433384/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment] 2020-10-25 18:53
Unfortunately I can't directly correlate AuraConnect being the reason why peoples PCs won't sleep. My PC sleeps fine with it running.

In the past I believe someone found unplugging a Razer headphone stand with a wireless dongle in it to fix their issue. It could be many things, I have had sleep issues not related to AuraConnect in the past before I even made it. Random software and devices and in some cases windows itself can cause sleep issues.

**Comment by noahjcorwin** [comment] 2020-10-27 00:12
I can confirm that Aura Connect service is the cause of my system not sleeping. Fresh install of W10 2004, ROG-Strix-X570-I with the latest bios of 2802 (2020/10/23), GSkill Trident Z Neo. Latest AMD chipset drivers 2.10.13.408, Armoury Crate 3.1.5, Aura Service 3.04.22.  I set the power setting to sleep after one minute, disable the Aura Connect service, don't touch the system, and it sleeps.  Wake the system, restart Aura Connect service, don't touch the system, and it will never sleep.  Let me know if there are further details that I can provide.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5442136/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment] 2020-10-27 01:22
I see the issue is that it's people who set their pc to auto sleep (I disable this explicitly because I don't like my PC sleeping automatically, I do manual sleeps which work fine).

This looks to be an issue in .NET Core with the way it handles worker services. This may be fixed in .NET 5. I however have no plans to migrate the service to .NET 5 at least until it's GA and soon it will instead be ran as a user process in the background and rewritten in c++ soon-ish. This isn't even to address this issue, it's actually just to increase performance. The side effect being that this should also fix sleeping issues.

There's nothing I can immediately do to fix this issue.

**Comment by noahjcorwin** [comment] 2020-10-27 14:51
That sounds great, I look forward to the new release. Thanks for this awesome software.

**Comment by AndrewBabbitt97** [comment] 2021-03-04 03:28
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl

**Closed by AndrewBabbitt97** 2021-03-04 03:28 UTC
