### ISSUE TITLE
It looks not on on Synaps and does not work.

### ISSUE THREAD

**Issue by wout-junius** [AndrewBabbitt97/AuraConnect#28] opened 2020-03-31 08:47 UTC
I dont know how to set it in Aura Sync application but it just doesn't work.
i put my Ayra Sync on Default.
And in synaps it should be on rainbow cycle.
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/4407743/AuraConnect.log)
![Capture](https://user-images.githubusercontent.com/17813748/78006184-f7274780-733c-11ea-8dc6-73347662317f.PNG)

**Comment by jdfosterarmy** [comment] 2020-03-31 09:21
what version of auraconnect do you have installed?
Also if this is your first time running it, you may need to copy the effects to the "aura" circle. this happens to me once in a while, even on other 3rd party connect software (thermaltake for example).

If that doesn't fix it, create a new chroma profile then copy effects to everything to test it out. if it is still not working, try exiting out of all razer software and restart aura connect. Then restart aura connect. once it is running, then go ahead and start up synapse 3.

**Comment by wout-junius** [comment] 2020-03-31 09:38
> what version of auraconnect do you have installed?
> Also if this is your first time running it, you may need to copy the effects to the "aura" circle. this happens to me once in a while, even on other 3rd party connect software (thermaltake for example).
> 
> If that doesn't fix it, create a new chroma profile then copy effects to everything to test it out. if it is still not working, try exiting out of all razer software and restart aura connect. Then restart aura connect. once it is running, then go ahead and start up synapse 3.

After restarting it it works but now i got a known issue of unreachable.
Thx for helping me :)

**Comment by AndrewBabbitt97** [comment] 2020-03-31 13:31
Unreachable usually means antivirus/anticheat software interfering.

**Comment by wout-junius** [comment] 2020-03-31 13:33
> Unreachable usually means antivirus/anticheat software interfering.

Well i run no active antivirus atm so it must be Battle Eye as the other problem

**Comment by AndrewBabbitt97** [comment] 2020-03-31 13:41
Duplicate of #23 

Closing this issue, please continue the conversation there.

**Closed by AndrewBabbitt97** 2020-03-31 13:41 UTC
Labels: duplicate
