### ISSUE TITLE
Not sync with visualizer or games 

### ISSUE THREAD

**Issue by AldoMagallon95** [AndrewBabbitt97/AuraConnect#89] opened 2020-10-12 04:03 UTC
Hello 
I dont remember exactly since when but when i open a game like overwatch, rise of the tomb raider or apex and/or trying to sync with the visualizer the efect doesnt sync with the asus aura and it just stops and doesnt do anything.

**Comment by AndrewBabbitt97** [comment] 2020-10-12 04:30
Have you followed all troubleshooting steps in the readme?

After you have done so if you still have issues, need your log files from c:\programdata\auraconnect\logs

**Comment by jedi117** [comment] 2020-10-12 04:36
yes i have tried the steps but nothing seems to work, her is my log
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5362923/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment] 2020-10-12 04:50
Turn on perf metrics, doesn't look like Synapse is sending messages to AuraConnect:

https://github.com/AndrewBabbitt97/AuraConnect/blob/master/docs/PerformanceMetrics.md

**Comment by jedi117** [comment] 2020-10-12 05:04
i did it but still the same i even uninstall it and install it again but still the same i tried to sync with visualizer but as soon as i trun on the visualizer the effect is only shown in the keyboard and mouse

**Comment by AndrewBabbitt97** [comment] 2020-10-12 05:17
The point of turning on perf logging is so that your logs have more details that I can use for debugging.

I need your log after you have had perf metrics on and you have encountered the error.

**Comment by jedi117** [comment] 2020-10-12 05:27
[AuraConnect.log](https://github.com/AndrewBabbitt97/AuraConnect/files/5363072/AuraConnect.log)

**Comment by AndrewBabbitt97** [comment] 2020-10-12 05:40
I see the service restarted at the end of the log and no more messages after that. Did you restart the service? What happened there?

Otherwise it looks like AURA is getting all the messages. So it's likely something is wrong with your Aura installation or something on your PC preventing messages from being sent to AURA.

As far as I can tell, this error is entirely on the Synapse or Aura side on your PC. This could be a corrupt file, a rouge AV software, anti-cheat software, or so many other things that you could have installed on your PC. I use this software every day for 10+ hours without issue, and it's been insanely stable since I rebuilt my PC a few months ago without ever having to do anything. Chances are theres something specific going wrong with some software on your PC. (Be aware that 99% of errors stem from Aura or Synapse and not AuraConnect, we have ironed out all the AuraConnect specific issues AFAIK).

**Comment by jedi117** [comment] 2020-10-12 05:56
maybe is when i uninstalled and installed and reebot my pc. I
 built my pc some weeks ago and i dont have anything else more than games and some work papers at the beginning everything worked fine but i think after a razer update it stoped to sync for games and visualizer.

**Comment by jedi117** [comment] 2020-10-12 17:08
actually the effects are only with visualizer and games that doesnt work, but with other razer effects works fine

**Comment by gothaussen** [comment] 2020-10-12 19:33
I have the same problem, they don't synchronize Aura with visualizer or games

**Comment by bigbutler** [comment] 2020-10-15 12:50
same problem visualizer or games dont work :(

**Comment by LAbornTXraised** [comment] 2020-10-20 01:10
I'm running into the same issue. Every studio feature works, but visualizer and game takeover doesn't work.

**Comment by AndrewBabbitt97** [comment] 2020-10-25 19:36
Can confirm at least on the visualizer side that this functionality is broken in Synapse. Nothing I can do about it however.

**Comment by Hotpepere** [comment] 2020-10-30 09:53
pour information c'est un probleme connu chez razer et ils travaillent a la resolution
[https://insider.razer.com/index.php?threads/visualiser-stopped-controlling-thermaltake-fans.64797/]

**Comment by bigbutler** [comment] 2020-11-07 01:05
The Razer support say aura sync prob i say  is a sdk prob

**Comment by AndrewBabbitt97** [comment] 2020-11-07 01:52
I have contacts at razer on the chroma side of things.

We discussed the issue, its because AuraConnect is running as a system process. Recent update to Synapse broke it being able to run as a system process. I have an update coming out this weekend to address the isssue.

**Comment by jedi117** [comment] 2020-11-07 01:55
Thank you very much

**Comment by bigbutler** [comment] 2020-11-07 02:04
> I have contacts at razer on the chroma side of things.
> 
> We discussed the issue, its because AuraConnect is running as a system process. Recent update to Synapse broke it being able to run as a system process. I have an update coming out this weekend to address the isssue.

appreciate your work

**Comment by AndrewBabbitt97** [comment] 2020-11-07 02:10
Workaround:
Right click task bar -> Task Manager -> Services tab -> Open Services on the bottom of the window

Find the AuraConnect service in the list, right click it and stop it

![1](https://user-images.githubusercontent.com/2308261/98429255-da858780-2062-11eb-8a49-16469089abe8.png)

Right click again, click properties and go to Log On tab

![1](https://user-images.githubusercontent.com/2308261/98429296-1fa9b980-2063-11eb-8ed8-72051f361863.png)

Change from local system account to this account and enter your windows account details

![1](https://user-images.githubusercontent.com/2308261/98429369-63042800-2063-11eb-9e7f-ccc74ff4aead.png)

Press ok

Go to "C:\ProgramData\AuraConnect\logs" and delete the AuraConnect.log file

Start the service again, should be good

**Comment by bigbutler** [comment] 2020-11-09 10:38
> I have contacts at razer on the chroma side of things.
> 
> We discussed the issue, its because AuraConnect is running as a system process. Recent update to Synapse broke it being able to run as a system process. I have an update coming out this weekend to address the isssue.

Monday no update :( 
I think problem is unsolved :(

**Comment by AndrewBabbitt97** [comment] 2020-11-09 10:54
I'm buying developer certificate for signing before I can release. This isn't just a minor update, it's an entirely new way to install and run the software.

**Comment by AndrewBabbitt97** [comment] 2020-11-09 11:02
Changes in #54 will start as of the next update. There's a lot more changes to this, didn't get as much time to work on this this weekend as I would have liked.

**Comment by bigbutler** [comment] 2020-11-09 18:03
okay 
You Workaround dont work.

**Comment by LAbornTXraised** [comment] 2020-11-09 18:31
Yeah the workaround didn't work for me either, but I'm fine waiting on the update.

**Comment by KyleStilkey** [comment] 2020-11-11 09:16
Work around didn't work here as well. Excited for the new update release. Keep up the good work man!

**Comment by Sajyd** [comment] 2020-11-15 20:31
It stopped working a few days ago but now it just started wroking back today

**Comment by josemahj** [comment] 2020-11-15 20:39
> It stopped working a few days ago but now it just started working back again today

synapse version?

**Comment by bigbutler** [comment] 2020-11-15 22:40
> It stopped working a few days ago but now it just started working back again today

blabla

**Comment by AndrewBabbitt97** [comment] 2020-11-15 23:19
I would highly recommend the ARGB controller anyways due to being able to individually control devices.

As for those that it randomly started working for: did you get a Synapse update?

**Comment by joyarup** [comment] 2020-11-16 04:16
> It stopped working a few days ago but now it just started working back again today

What's your synapse version?

**Comment by Sajyd** [comment] 2020-11-16 06:22
Looks like synapse version hasn't changed -> 3.5.1030.101917
I was checking this post 2 days ago because it wasn't working for a long time then it worked back yesterday. 

> > It stopped working a few days ago but now it just started working back again today
> 
> blabla
> 
> I don't believe it any more
> I buy me a Razer Argb Hub Controll on Synapse 3.

I'm only talking about AuraConnect sync of course. Official Razer keyboard was working fine

**Comment by joyarup** [comment] 2020-11-16 08:03
> Looks like synapse version hasn't changed -> 3.5.1030.101917
I see, which software are you using for motherboard, Aura Sync or Armory Crate?

**Comment by AndrewBabbitt97** [comment] 2020-11-16 08:20
The use of Aura vs Armory Crate is irrelevant in terms of this issue. The issue stems from an issue with Chroma SDK and the Broadcast API from Razer and how they interact in session 0. It's weird for it to randomly start working however.

**Comment by Hotpepere** [comment] 2020-11-16 11:36
personnellement cela ne marche pas du tout même après l'application des solutions temporaire que tu proposais
Je n'ai pas eu de mise a jour de synapse3 depuis un certain temps d'ailleurs.
Cela m’étonne aussi que cela remarche aléatoirement, je pense qu'il y a erreur
j'ai commandé le controller ARGB razer pour toutes mes bandes a leds + ventilateurs
N'oubliez pas que si vos éléments tel que bandes a LED et ventilateurs étaient branchés sur votre carte mère ,vous avez une chance sur 2 que ce soit du RGB standard 4 broches 12V.
le controller RAZER gère des leds RGB adressable et donc 3 broches 5v -> il vous faudra changer toutes vos leds par de la led adressable et les remplacer sur vos ventilateurs si vous êtes bricoleurs ou racheter des ventilateurs
ce n'est pas du plug and play

Andrew ou en ais tu de tes démarches administratives? a tu pus avancer sur la mise a jour de ton logiciel, il me manque  :)

**Comment by AndrewBabbitt97** [comment] 2020-11-16 11:49
If we can please try to keep conversation to english, if you speak another language providing a translation to english would be preferred.

**Comment by bigbutler** [comment] 2020-11-16 23:54
> If we can please try to keep conversation to english, if you speak another language providing a translation to english would be preferred.

Let's be honest you can patch it at all I don't think because it's an SDK problem. Why do you claim it comes a patch that with the licens is mischief,
Complete and Close this project and take care of other projects.
they admit because it has failed.
you are only a Human.

**Comment by AndrewBabbitt97** [comment] 2020-11-17 00:14
> > If we can please try to keep conversation to english, if you speak another language providing a translation to english would be preferred.
> 
> Let's be honest you can patch it at all I don't think because it's an SDK problem. Why do you claim it comes a patch that with the licens is mischief,
> Complete and Close this project and take care of other projects.
> they admit because it has failed.
> you are only a Human.

This is a bit excessive. This project has over 30k downloads. It is an SDK problem, I have discussed so with the devs and confirmed it myself.

This is one minor issue, the project itself works. The only issue has been with Chroma SDK. Studio works fine. If you got a problem with the project and it's causing you distress, don't use it.

**Comment by bigbutler** [comment] 2020-11-17 00:51
I'm coder if a company programs an SDK incorrectly why should you bathe it yourself what others can't? I think that is a waste of time. I respect your work. Mine so only that you could make yourself better projects that bring more downloads. or wait are these idiots fixing the SDK.

**Comment by bigbutler** [comment] 2020-11-21 17:49
yeah is see how it works xD

**Comment by arkhos** [comment] 2020-11-24 15:15
> Workaround:
> Right click task bar -> Task Manager -> Services tab -> Open Services on the bottom of the window
> 
> Find the AuraConnect service in the list, right click it and stop it
> 
> ![1](https://user-images.githubusercontent.com/2308261/98429255-da858780-2062-11eb-8a49-16469089abe8.png)
> 
> Right click again, click properties and go to Log On tab
> 
> ![1](https://user-images.githubusercontent.com/2308261/98429296-1fa9b980-2063-11eb-8ed8-72051f361863.png)
> 
> Change from local system account to this account and enter your windows account details
> 
> ![1](https://user-images.githubusercontent.com/2308261/98429369-63042800-2063-11eb-9e7f-ccc74ff4aead.png)
> 
> Press ok
> 
> Go to "C:\ProgramData\AuraConnect\logs" and delete the AuraConnect.log file
> 
> Start the service again, should be good

Works for me, thanks!

**Comment by Hotpepere** [comment] 2020-11-27 19:14
Hello
The new update razer synapse solved the problem of itself without any modification.
I had already applied weeks before the user rights solution developed earlier in the topic
So I applied the razer update directly
Everything is working again, and auraconnect was not at the origin of the problem as Andrew told us
you had to be confident and patient

**Comment by joyarup** [comment] 2020-11-27 19:34
> Hello
> The new update razer synapse solved the problem of itself without any modification.
> I had already applied weeks before the user rights solution developed earlier in the topic
> So I applied the razer update directly
> Everything is working again, and auraconnect was not at the origin of the problem as Andrew told us
> you had to be confident and patient

Hey, when did you get the synapse update, today? and what's your synapse version currently.
And yes, as Andrew said.. it is the Chroma SDK problem.

**Comment by josemahj** [comment] 2020-11-27 22:56
> Hello
> The new update razer synapse solved the problem of itself without any modification.
> I had already applied weeks before the user rights solution developed earlier in the topic
> So I applied the razer update directly
> Everything is working again, and auraconnect was not at the origin of the problem as Andrew told us
> you had to be confident and patient

not to me, still broken. now leds stop and flick when launch apex, before update leds simply stop effect.

**Comment by bigbutler** [comment] 2020-11-28 15:56
you need to update armory crate 3.2.4.0 and Service/hal Synapse 3.5.11.30.111812 Restart pc and Games Sync work.

**Comment by joyarup** [comment] 2020-11-28 16:43
I still didn't get the update in synapse, I think it will come eventually.. Hope it will solve it.

**Comment by KyleStilkey** [comment] 2020-12-01 04:20
Just updating here as well, seems Razer put a fix in place for this. Got the update a few days ago and was able to test and it's operating as normal again.

**Comment by jedi117** [comment] 2020-12-01 04:24
i already tested on the newest update and worked again for visualizer and games

**Comment by LAbornTXraised** [comment] 2020-12-04 19:49
After Razer update it has begun working again for me as well

**Comment by AndrewBabbitt97** [comment] 2021-03-04 03:28
AuraConnect has been archived, please move onto the replacement ChromaControl: https://github.com/ChromaControl/ChromaControl

**Closed by AndrewBabbitt97** 2021-03-04 03:28 UTC
